services:
  backend:
    image: kevinvnguyen97/adventure-routes-backend
    container_name: adventure-routes-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./shared:/app/shared

  frontend:
    image: kevinvnguyen97/adventure-routes-frontend
    container_name: adventure-routes-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./shared:/app/shared

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - ./backend/.env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
